AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - "tmp/**/*"
    - "log/**/*"
    - 'node_modules/**/*'
    - 'vendor/**/*'

# Rails specific

require: rubocop-rails

Rails/OutputSafety:
  Enabled: false # This disallows .html_safe
Rails/TimeZone:
  Enabled: false # This enforces Time.zone.now
Rails/Date:
  Enabled: false # This enforces Time.zone.today
Rails/HasAndBelongsToMany:
  Enabled: false # This disallows HABTM.

# Project styling

Style/IfUnlessModifier:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/LineLength:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'app/admin/**/*'
    - 'spec/**/*_spec.rb'
    - 'config/**/*'
    - 'spec/factories/*'
Lint/ShadowingOuterLocalVariable: # shadowing is a language feature - we should use it where appropriate.
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true

# Concessions (remove these if possible / appropriate).

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false # TODO: Enable this once it stops begin buggy. https://github.com/rubocop-hq/rubocop/issues/7212
Bundler/OrderedGems:
  Enabled: false # we have a ton of gems, grouped arbitrarily. Could be tackled later.
Style/FrozenStringLiteralComment:
  Enabled: false # forces addition of frozen string literal directive to all files. WTF.
Metrics/MethodLength:
  Max: 20 # default was 10.
Metrics/ClassLength:
  Max: 500 # default was 100.
Metrics/AbcSize:
  Max: 30 # default is 15.
Style/GuardClause:
  Enabled: false # this thing is annoying, and can lead to not-as-readable code.
Style/YodaCondition:
  Enabled: false # buggy - sometimes complains about fixed code, and autocorrect doesn't work.
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false # buggy
