# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
common: &common
  intercom_secure_mode_secret_key: <%= ENV['INTERCOM_SECURE_MODE_SECRET_KEY'] %>
  slack_memberships_webhook_url: <%= ENV['SLACK_MEMBERSHIPS_WEBHOOK_URL'] %>
  slack_token: <%= ENV['SLACK_APP_BOT_OAUTH_TOKEN'] %>
  intercom_access_token: <%= ENV['INTERCOM_ACCESS_TOKEN'] %>
  aws:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    bucket: <%= ENV['AWS_BUCKET'] %>
  trello:
    app_key: <%= ENV['TRELLO_APP_KEY'] %>
    api_token: <%= ENV['TRELLO_API_TOKEN'] %>
    rollbar_list_id: <%= ENV['TRELLO_ROLLBAR_LIST_ID'] %>
    engineering_board_id: <%= ENV['TRELLO_ENGINEERING_BOARD_ID'] %>
    bug_label_id: <%= ENV['TRELLO_BUG_LABEL_ID'] %>
  intercom:
    secure_mode_secret_key: <%= ENV['INTERCOM_SECURE_MODE_SECRET_KEY'] %>
    prune_segments:
      archive: <%= ENV['INTERCOM_PRUNE_SEGMENTS_ARCHIVE'] %>
      delete: <%= ENV['INTERCOM_PRUNE_SEGMENTS_DELETE'] %>
  slack:
    name: <%= ENV['SLACK_NAME'] %>
    app:
      client_id: "<%= ENV['SLACK_APP_CLIENT_ID'] %>"
      client_secret: <%= ENV['SLACK_APP_CLIENT_SECRET'] %>
      oauth_token: <%= ENV['SLACK_APP_OAUTH_TOKEN'] %>
      bot_oauth_token: <%= ENV['SLACK_APP_BOT_OAUTH_TOKEN'] %>
    channels:
      public: <%= ENV['SLACK_CHANNELS_PUBLIC'] %>
      private: <%= ENV['SLACK_CHANNELS_PRIVATE'] %>
    team_ids:
      public_slack: <%= ENV['SLACK_TEAM_IDS_PUBLIC_SLACK'] %>
  send_in_blue:
    v3_api_key: <%= ENV['SEND_IN_BLUE_V3_API_KEY'] %>
    v2_api_key: <%= ENV['SEND_IN_BLUE_V2_API_KEY'] %>
  zoom:
    api_key: <%= ENV['ZOOM_API_KEY'] %>
    api_secret: <%= ENV['ZOOM_API_SECRET'] %>
    host_user_id: <%= ENV['ZOOM_HOST_USER_ID'] %>
  typeform:
    screening_url: <%= ENV['TYPEFORM_SCREENING_URL'] %>
  sso_domain: <%= ENV['SSO_DOMAIN'] %>
  max_daily_markdown_attachments: <%= ENV['MAX_DAILY_MARKDOWN_ATTACHMENTS']&.to_i || 50 %>

development:
  secret_key_base: "2ab04e6d7919f4f9fd1e25d41455aa26ad21c2a8d053bc00ac02db4d424d97e0716105c620907e6d829329fe275d52673117d432d6d00c9052bec26a82b2de3f"
  <<: *common

test:
  aws:
    access_key_id: test_access_key
    secret_access_key: test_secret_access_key
    bucket: test-bucket
  sso_domain: sso.test.host
  secret_key_base: "fc12d0f63b32c108fad70c1ed5e2502860ea4d59ca8c51f5606c0ff2d8a6eed8ed66bb090e6040b91eccf789d76651b17b5bf522e3611f18967b514560b028de"
  slack_token: 'BOT_OAUTH_TOKEN'
  slack_general_webhook_url: 'http://example.com/slack'
  intercom_access_token: 'test_intercom_access_token'
  intercom:
    prune_segments:
      archive: <%= '{"Stale Applicants - Last Seen Known":"Stale Applicants","Stale Applicants - Last Seen Unknown":"Stale Applicants","Stale Leads - Email - Last Seen Known":"Stale Leads","Stale Leads - Email - Last Seen Unknown":"Stale Leads"}' %>
      delete: <%= '["Clean Up Leads - Delete often","Clean Up Leads - Delete often 2"]' %>
  slack:
    name: 'sv'
    app:
      client_id: 'CLIENT_ID'
      client_secret: 'CLIENT_SECRET'
      oauth_token: 'OAUTH_TOKEN'
      bot_oauth_token: 'BOT_OAUTH_TOKEN'
    team_ids:
      public_slack: 'XYZ1234'
    channels:
      public:
        - public-channel
      private:
        - private-channel
  send_in_blue:
    v3_api_key: <%= ENV['SEND_IN_BLUE_V3_API_KEY'] %>
    v2_api_key: 'test_sendinblue_v2_api_key'
  zoom:
    api_key: 'api_key'
    api_secret: 'api_secret'
    host_user_id: 'host_user_id'
  typeform:
    screening_url: 'http://example.com/typeform'
  max_daily_markdown_attachments: 10

# Do not keep production secrets in the repository,
# instead read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  <<: *common
